### ISSUE TITLE
Strange routing

### ISSUE THREAD

**Issue by aodhol** [mapbox/MapboxDirections.swift#160]
This maybe the wrong project (though I'm seeing it using the iOS SDK - it's not limited to it), but Mapbox is giving me a very strange routing between these two (walking) points: 

https://api.mapbox.com/directions/v5/mapbox/walking/-0.059627%2C51.520344%3B-0.0582750%2C51.5195760.json?access_token=pk.eyJ1IjoiYW9kaG9sIiwiYSI6ImNqNTA1cjZvODBqbzcycXJzeXZkZ3Y2eHkifQ.zC88H73pX40A6FN-YNtocw

<img width="546" alt="screen shot 2017-08-08 at 00 43 24" src="https://user-images.githubusercontent.com/274682/29050268-cb6fedfe-7bd2-11e7-9f7f-05e4550862c4.png">

Versus Google: https://www.google.co.uk/maps/dir/+51.5195760,+-0.0582750/51.520344,-0.059627/

<img width="272" alt="screen shot 2017-08-08 at 00 45 22" src="https://user-images.githubusercontent.com/274682/29050292-ea713186-7bd2-11e7-805f-0710fed97d49.png">

**Comment by geografa** [comment]
@aodhol I've added your feedback here: https://www.mapbox.com/directions-feedback/mapbox/?profile=walking#15/-122.4365/37.7794

Since it happens at the API level, looks independent from MapboxDirections.swift so closing here for now.

**Comment by geografa** [comment]
Fixed with https://www.openstreetmap.org/changeset/51106301.

**Comment by aodhol** [comment]
@geografa I'm still seeing the issue, does it take some time to propagate?

**Comment by geografa** [comment]
@aodhol It's possible. Edits will take about a day. Here is the same route:
https://www.mapbox.com/directions-feedback/mapbox/?profile=walking&route=-0.05853652954101562,51.5195054401361;-0.059201717376708984,51.52050682892394#18/-0.05894/51.52001

Are you still unable to see this on your application? What are the source and library versions you are using?

**Comment by aodhol** [comment]
@geografa yes, this works fine now and has for a while. I think there was a delay of a day or two, however. Thanks very much!
